#############################################################################
# Makefile for building: ThemisLinux
# Generated by qmake (3.1) (Qt 6.11.2)
# Project:  ThemisLinux.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile ThemisLinux.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I. -I/usr/lib64/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ThemisLinux1.0.0
DISTDIR = /home/truonghieu/ThemisLinux/.tmp/ThemisLinux1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib64
LIBS          = $(SUBLIBS) -lz /usr/lib64/libQt6Widgets.so /usr/lib64/libQt6Gui.so /usr/lib64/libQt6Xml.so /usr/lib64/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MainWindow.cpp \
		SettingsParser.cpp \
		Judger.cpp \
		JudgeEngine.cpp \
		JudgeDialog.cpp \
		CompilerConfigDialog.cpp \
		TaskConfigDialog.cpp \
		DetailDialog.cpp \
		SecurityDialog.cpp \
		EnvSettingsDialog.cpp \
		Judger_win.cpp qrc_resources.cpp \
		moc_MainWindow.cpp \
		moc_JudgeEngine.cpp \
		moc_JudgeDialog.cpp \
		moc_CompilerConfigDialog.cpp \
		moc_TaskConfigDialog.cpp \
		moc_DetailDialog.cpp \
		moc_SecurityDialog.cpp \
		moc_EnvSettingsDialog.cpp
OBJECTS       = main.o \
		MainWindow.o \
		SettingsParser.o \
		Judger.o \
		JudgeEngine.o \
		JudgeDialog.o \
		CompilerConfigDialog.o \
		TaskConfigDialog.o \
		DetailDialog.o \
		SecurityDialog.o \
		EnvSettingsDialog.o \
		Judger_win.o \
		qrc_resources.o \
		moc_MainWindow.o \
		moc_JudgeEngine.o \
		moc_JudgeDialog.o \
		moc_CompilerConfigDialog.o \
		moc_TaskConfigDialog.o \
		moc_DetailDialog.o \
		moc_SecurityDialog.o \
		moc_EnvSettingsDialog.o
DIST          = /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gstreamermediapluginimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekit.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekit_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekitimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssynchronizer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltc_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserCore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserWidgets.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		ThemisLinux.pro MainWindow.h \
		SettingsParser.h \
		Judger.h \
		JudgeEngine.h \
		JudgeDialog.h \
		JudgeTypes.h \
		CompilerConfigDialog.h \
		TaskConfigDialog.h \
		DetailDialog.h \
		SecurityDialog.h \
		EnvSettingsDialog.h main.cpp \
		MainWindow.cpp \
		SettingsParser.cpp \
		Judger.cpp \
		JudgeEngine.cpp \
		JudgeDialog.cpp \
		CompilerConfigDialog.cpp \
		TaskConfigDialog.cpp \
		DetailDialog.cpp \
		SecurityDialog.cpp \
		EnvSettingsDialog.cpp \
		Judger_win.cpp
QMAKE_TARGET  = ThemisLinux
DESTDIR       = 
TARGET        = ThemisLinux


first: all
####### Build rules

ThemisLinux:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ThemisLinux.pro /usr/lib64/qt6/mkspecs/linux-g++/qmake.conf /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gstreamermediapluginimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekit.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekit_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekitimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssynchronizer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltc_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserCore.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserWidgets.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		ThemisLinux.pro \
		resources.qrc \
		/usr/lib64/libQt6Widgets.prl \
		/usr/lib64/libQt6Gui.prl \
		/usr/lib64/libQt6Xml.prl \
		/usr/lib64/libQt6Core.prl
	$(QMAKE) -o Makefile ThemisLinux.pro
/usr/lib64/qt6/mkspecs/features/spec_pre.prf:
/usr/lib64/qt6/mkspecs/common/unix.conf:
/usr/lib64/qt6/mkspecs/common/linux.conf:
/usr/lib64/qt6/mkspecs/common/sanitize.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt6/mkspecs/common/g++-base.conf:
/usr/lib64/qt6/mkspecs/common/g++-unix.conf:
/usr/lib64/qt6/mkspecs/qconfig.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gstreamermediapluginimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekit.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekit_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekitimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsstylekitimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssynchronizer.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labssynchronizer_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltc_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testinternals_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_tools_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserCore.pri:
/usr/lib64/qt6/mkspecs/modules/qt_MimeTreeParserWidgets.pri:
/usr/lib64/qt6/mkspecs/features/qt_functions.prf:
/usr/lib64/qt6/mkspecs/features/qt_config.prf:
/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt6/mkspecs/features/toolchain.prf:
/usr/lib64/qt6/mkspecs/features/default_pre.prf:
/usr/lib64/qt6/mkspecs/features/resolve_config.prf:
/usr/lib64/qt6/mkspecs/features/default_post.prf:
/usr/lib64/qt6/mkspecs/features/warn_on.prf:
/usr/lib64/qt6/mkspecs/features/permissions.prf:
/usr/lib64/qt6/mkspecs/features/qt.prf:
/usr/lib64/qt6/mkspecs/features/resources_functions.prf:
/usr/lib64/qt6/mkspecs/features/resources.prf:
/usr/lib64/qt6/mkspecs/features/moc.prf:
/usr/lib64/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt6/mkspecs/features/uic.prf:
/usr/lib64/qt6/mkspecs/features/unix/thread.prf:
/usr/lib64/qt6/mkspecs/features/qmake_use.prf:
/usr/lib64/qt6/mkspecs/features/file_copies.prf:
/usr/lib64/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt6/mkspecs/features/exceptions.prf:
/usr/lib64/qt6/mkspecs/features/yacc.prf:
/usr/lib64/qt6/mkspecs/features/lex.prf:
ThemisLinux.pro:
resources.qrc:
/usr/lib64/libQt6Widgets.prl:
/usr/lib64/libQt6Gui.prl:
/usr/lib64/libQt6Xml.prl:
/usr/lib64/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ThemisLinux.pro

qmake_all: FORCE


all: Makefile ThemisLinux

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents MainWindow.h SettingsParser.h Judger.h JudgeEngine.h JudgeDialog.h JudgeTypes.h CompilerConfigDialog.h TaskConfigDialog.h DetailDialog.h SecurityDialog.h EnvSettingsDialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp MainWindow.cpp SettingsParser.cpp Judger.cpp JudgeEngine.cpp JudgeDialog.cpp CompilerConfigDialog.cpp TaskConfigDialog.cpp DetailDialog.cpp SecurityDialog.cpp EnvSettingsDialog.cpp Judger_win.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib64/qt6/libexec/rcc \
		btnsecurity.png \
		btnloadcontestants.png \
		btnjudge.png \
		btnsettings.png \
		btnsavecontest.png \
		btnloadtasks.png \
		btnrefreshcontestants.png \
		btnrefreshtasks.png \
		btnnewcontest.png \
		btnopencontest.png \
		btnexport.png \
		btncompilerconfig.png
	/usr/lib64/qt6/libexec/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib64/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MainWindow.cpp moc_JudgeEngine.cpp moc_JudgeDialog.cpp moc_CompilerConfigDialog.cpp moc_TaskConfigDialog.cpp moc_DetailDialog.cpp moc_SecurityDialog.cpp moc_EnvSettingsDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_JudgeEngine.cpp moc_JudgeDialog.cpp moc_CompilerConfigDialog.cpp moc_TaskConfigDialog.cpp moc_DetailDialog.cpp moc_SecurityDialog.cpp moc_EnvSettingsDialog.cpp
moc_MainWindow.cpp: MainWindow.h \
		CompilerConfigDialog.h \
		JudgeEngine.h \
		JudgeTypes.h \
		SettingsParser.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/truonghieu/ThemisLinux/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/truonghieu/ThemisLinux -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include MainWindow.h -o moc_MainWindow.cpp

moc_JudgeEngine.cpp: JudgeEngine.h \
		JudgeTypes.h \
		SettingsParser.h \
		CompilerConfigDialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/truonghieu/ThemisLinux/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/truonghieu/ThemisLinux -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include JudgeEngine.h -o moc_JudgeEngine.cpp

moc_JudgeDialog.cpp: JudgeDialog.h \
		JudgeEngine.h \
		JudgeTypes.h \
		SettingsParser.h \
		CompilerConfigDialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/truonghieu/ThemisLinux/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/truonghieu/ThemisLinux -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include JudgeDialog.h -o moc_JudgeDialog.cpp

moc_CompilerConfigDialog.cpp: CompilerConfigDialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/truonghieu/ThemisLinux/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/truonghieu/ThemisLinux -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include CompilerConfigDialog.h -o moc_CompilerConfigDialog.cpp

moc_TaskConfigDialog.cpp: TaskConfigDialog.h \
		SettingsParser.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/truonghieu/ThemisLinux/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/truonghieu/ThemisLinux -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include TaskConfigDialog.h -o moc_TaskConfigDialog.cpp

moc_DetailDialog.cpp: DetailDialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/truonghieu/ThemisLinux/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/truonghieu/ThemisLinux -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include DetailDialog.h -o moc_DetailDialog.cpp

moc_SecurityDialog.cpp: SecurityDialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/truonghieu/ThemisLinux/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/truonghieu/ThemisLinux -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include SecurityDialog.h -o moc_SecurityDialog.cpp

moc_EnvSettingsDialog.cpp: EnvSettingsDialog.h \
		moc_predefs.h \
		/usr/lib64/qt6/libexec/moc
	/usr/lib64/qt6/libexec/moc $(DEFINES) --include /home/truonghieu/ThemisLinux/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/truonghieu/ThemisLinux -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtXml -I/usr/include/qt6/QtCore -I/usr/include/c++/16 -I/usr/include/c++/16/x86_64-redhat-linux -I/usr/include/c++/16/backward -I/usr/lib/gcc/x86_64-redhat-linux/16/include -I/usr/local/include -I/usr/include EnvSettingsDialog.h -o moc_EnvSettingsDialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp MainWindow.h \
		CompilerConfigDialog.h \
		JudgeEngine.h \
		JudgeTypes.h \
		SettingsParser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		CompilerConfigDialog.h \
		JudgeEngine.h \
		JudgeTypes.h \
		SettingsParser.h \
		SecurityDialog.h \
		EnvSettingsDialog.h \
		JudgeDialog.h \
		TaskConfigDialog.h \
		DetailDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

SettingsParser.o: SettingsParser.cpp SettingsParser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SettingsParser.o SettingsParser.cpp

Judger.o: Judger.cpp Judger.h \
		JudgeTypes.h \
		CompilerConfigDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Judger.o Judger.cpp

JudgeEngine.o: JudgeEngine.cpp JudgeEngine.h \
		JudgeTypes.h \
		SettingsParser.h \
		CompilerConfigDialog.h \
		Judger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JudgeEngine.o JudgeEngine.cpp

JudgeDialog.o: JudgeDialog.cpp JudgeDialog.h \
		JudgeEngine.h \
		JudgeTypes.h \
		SettingsParser.h \
		CompilerConfigDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JudgeDialog.o JudgeDialog.cpp

CompilerConfigDialog.o: CompilerConfigDialog.cpp CompilerConfigDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CompilerConfigDialog.o CompilerConfigDialog.cpp

TaskConfigDialog.o: TaskConfigDialog.cpp TaskConfigDialog.h \
		SettingsParser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TaskConfigDialog.o TaskConfigDialog.cpp

DetailDialog.o: DetailDialog.cpp DetailDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DetailDialog.o DetailDialog.cpp

SecurityDialog.o: SecurityDialog.cpp SecurityDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SecurityDialog.o SecurityDialog.cpp

EnvSettingsDialog.o: EnvSettingsDialog.cpp EnvSettingsDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EnvSettingsDialog.o EnvSettingsDialog.cpp

Judger_win.o: Judger_win.cpp Judger.h \
		JudgeTypes.h \
		CompilerConfigDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Judger_win.o Judger_win.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_JudgeEngine.o: moc_JudgeEngine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_JudgeEngine.o moc_JudgeEngine.cpp

moc_JudgeDialog.o: moc_JudgeDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_JudgeDialog.o moc_JudgeDialog.cpp

moc_CompilerConfigDialog.o: moc_CompilerConfigDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CompilerConfigDialog.o moc_CompilerConfigDialog.cpp

moc_TaskConfigDialog.o: moc_TaskConfigDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TaskConfigDialog.o moc_TaskConfigDialog.cpp

moc_DetailDialog.o: moc_DetailDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DetailDialog.o moc_DetailDialog.cpp

moc_SecurityDialog.o: moc_SecurityDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SecurityDialog.o moc_SecurityDialog.cpp

moc_EnvSettingsDialog.o: moc_EnvSettingsDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_EnvSettingsDialog.o moc_EnvSettingsDialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

